drop table RAW_REPORT;
drop table PERSON;

create table RAW_REPORT(
DATE VARCHAR(100) NOT NULL,
IMPRESSIONS VARCHAR(100) NOT NULL,
CLICKS VARCHAR(40) NOT NULL,
EARNING VARCHAR(40) NOT NULL
);

CREATE TABLE PERSON(
    ID INTEGER,
    NAME VARCHAR (50),
    SURNAME VARCHAR (50),
    EMAIL VARCHAR (50),
	GENDER VARCHAR (4),
    PRIMARY KEY (ID)
);
